### ISSUE TITLE
Wayland: Window not visible / Couldn't create shared context hidden window

### ISSUE THREAD

**Issue by gravit0** [GTNewHorizons/lwjgl3ify#101]
I try run lwjgl3ify with libglfw wayland:
```
java.lang.RuntimeException: org.lwjglx.LWJGLException: Couldn't create shared context hidden window
	at cpw.mods.fml.client.SplashProgress.start(SplashProgress.java:199)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:193)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:146)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:31)
```
I try off loading screen in `splash.properties`. 
Now the game starts, the window is displayed in the taskbar, the music plays, but the window is invisible. Resize, Fullscreen, etc. does not work. Closing by leading an icon and clicking button 'close' - works

System:
- ArchLinux
- KDE 6 Beta
- NVIDIA 545.29

I tested with Optifine and without it

**Comment by umbrageodotus** [comment]
Actually, I believe you no longer should use libglfw wayland. Use the system native GLFW and I believe it's wayland-native when possible.
