### ISSUE TITLE
Crash with modpack

### ISSUE THREAD

**Issue by reuben-matus** [GTNewHorizons/lwjgl3ify#117]
using lwjgl3ify with my modpack on linux gives the following error:
```
[01:08:17] [Client thread/ERROR] [FML]: Fatal errors were detected during the transition from CONSTRUCTING to PREINITIALIZATION. Loading cannot continue
[01:08:17] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[01:08:17] [Client thread/ERROR] [FML]: Caught exception from lwjgl3ify
java.lang.NoClassDefFoundError: org/lwjgl/Version
	at me.eigenraven.lwjgl3ify.ClientProxy.<clinit>(ClientProxy.java:22) ~[lwjgl3ify-2.0.0-alpha-2-snapshot.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_392]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_392]
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_392]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_392]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_392]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_392]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_392]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_392]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:6993) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_392]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_392]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_392]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_392]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: org.lwjgl.Version
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_392]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_392]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_392]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_392]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_392]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_392]
	... 39 more

mods in modpack:
UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UC	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UC	CodeChickenCore{1.2.1} [CodeChicken Core] (minecraft.jar) 
	UC	NotEnoughItems{2.3.32-GTNH} [NotEnoughItems] (NotEnoughItems-2.3.32-GTNH.jar) 
	UC	redirectionor{1.7.10} [Redirectionor] (minecraft.jar) 
	UC	smoothfontcore{1.7.10-1.15.1} [Smooth Font Core] (minecraft.jar) 
	UC	FoamFixCore{1.0.4} [FoamFixCore] (minecraft.jar) 
	UC	smoothfont{1.7.10-1.15.3} [Smooth Font] (SmoothFont-1.7.10-1.15.3.jar) 
	UC	unimixins{0.1.15} [UniMixins] (+unimixins-all-1.7.10-0.1.15.jar) 
	UC	unimixins-mixin{0.1.15} [UniMixins: Mixin (UniMix)] (+unimixins-all-1.7.10-0.1.15.jar) 
	UC	unimixins-compat{0.1.15} [UniMixins: Compatibility] (+unimixins-all-1.7.10-0.1.15.jar) 
	UC	mixingasm{0.3} [UniMixins: Mixingasm] (+unimixins-all-1.7.10-0.1.15.jar) 
	UC	spongemixins{2.0.1} [UniMixins: SpongeMixins] (+unimixins-all-1.7.10-0.1.15.jar) 
	UC	mixinbooterlegacy{1.2.1} [UniMixins: MixinBooterLegacy] (+unimixins-all-1.7.10-0.1.15.jar) 
	UC	gasstation{0.5.1} [UniMixins: GasStation] (+unimixins-all-1.7.10-0.1.15.jar) 
	UC	gtnhmixins{2.2.0} [UniMixins: GTNHMixins] (+unimixins-all-1.7.10-0.1.15.jar) 
	UC	mixinextras{0.1.15} [UniMixins: MixinExtras] (+unimixins-all-1.7.10-0.1.15.jar) 
	UC	customnpcs{1.8.6} [CustomNPC+] (CustomNPC-Plus-1.8.6.jar) 
	UC	flansmod{1.57} [Flan's Mod Ultimate] (Flans_Mod_Ultimate_Stability_Edition-1.57.jar) 
	UC	wolffsmod{6.0.2} [Flan's Mod NPC Vehicles] ([1.7.10]+Flan's+Mod+NPC+Vehicles-6.0.2.jar) 
	UC	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UC	aiimprovements{0.0.1.8} [AI Improvements] (AIImprovements-1.7.10-0.0.1b8.jar) 
	UC	AncientWarfare{3.0.1-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-3.0.1-beta-MC1.7.10-FULL.jar) 
	UC	AncientWarfareAutomation{3.0.1-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-3.0.1-beta-MC1.7.10-FULL.jar) 
	UC	AncientWarfareModeler{3.0.1-beta-MC1.7.10} [Ancient Warfare Model Editor] (ancientwarfare-3.0.1-beta-MC1.7.10-FULL.jar) 
	UC	AncientWarfareStructure{3.0.1-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-3.0.1-beta-MC1.7.10-FULL.jar) 
	UC	AncientWarfareNEIPlugin{3.0.1-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-3.0.1-beta-MC1.7.10-FULL.jar) 
	UC	AncientWarfareNpc{3.0.1-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-3.0.1-beta-MC1.7.10-FULL.jar) 
	UC	archaicfix{0.7.0fork5reup2} [ArchaicFix] (archaicfix-v0.7FORK5.jar) 
	UC	bugtorch{GRADLETOKEN_VERSION} [BugTorch] (bugtorch-1.2.3.jar) 
	UC	butterflymania{1.3.2} [Butterfly Mania] (butterflymania-1.7.10-1.3.2.jar) 
	UC	campfirebackport{1.7.10-1.10.1} [Campfire Backport] (campfirebackport-1.7.10-1.10.1.jar) 
	UC	chunkpregenerator{2.5.0} [Chunk Pregenerator] (Chunk+Pregenerator-V1.7.10-2.5.3.jar) 
	UC	coretweaks{0.3.3.2} [CoreTweaks] (CoreTweaks-1.7.10-0.3.3.2+nomixin.jar) 
	UC	jinryuujrmcore{1.3.51} [JinRyuu's JRMCore] (JRMCore-v1.3.51.jar) 
	UC	jinryuudragonblockc{1.4.83} [Dragon Block C] (DragonBlockC-v1.4.83.jar) 
	UC	entityculling{1.0.1} [Entity Culling Unofficial] (EC-Unofficial-1.0.1.jar) 
	UC	etfuturum{2.6.0fork8} [Et Futurum Requiem] (Et_Futurum_Requiem-2.6.0fork10.jar) 
	UC	falsepatternlib{1.0.0} [FalsePatternLib] (falsepatternlib-mc1.7.10-1.0.0.jar) 
	UC	falsetweaks{2.8.1.dirty} [FalseTweaks] (falsetweaks-mc1.7.10-2.8.1.dirty.jar) 
	UC	foamfix{@VERSION@} [FoamFix] (FoamFix-1.7.10-universal-1.0.4.jar) 
	UC	gtnhlib{0.2.1} [GTNH Lib] (gtnhlib-0.2.1.jar) 
	UC	hodgepodge{2.4.12} [Hodgepodge] (hodgepodge-2.4.12.jar) 
	UC	jinryuubetterrenderaddon{1.6.52} [JinRyuu's Better Render Addon] (JBRA-Client-v1.6.52.jar) 
	UC	jinryuufamilyc{1.2.18} [JinRyuu's Family C] (JFamilyC-v1.2.18.jar) 
	UC	jinryuuhdskinsextended{1.3.1} [JinRyuu's HD Skins Extended] (JinRyuu's-HDSkins-Mod-1.7.10-v1.3.1.jar) 
	UC	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited (1).jar) 
	UC	jaff{1.4.2_for_1.7.10} [Just a Few Fish] (JustAFewFish-1.4.2_for_1.7.10.jar) 
	UC	jinryuuyearsc{1.2.5} [JinRyuu's Years C] (JYearsC-v1.2.5.jar) 
	UE	lwjgl3ify{2.0.0-alpha-2-snapshot} [lwjgl3ify] (lwjgl3ify-2.0.0-alpha-2-snapshot.jar) 
	UC	naturescompass{1.3.1} [Nature's Compass] (NaturesCompass-1.7.10-1.3.1.jar) 
	UC	netherlicious{3.2.8} [Netherlicious] (netherlicious-3.2.8.jar) 
	UC	notenoughpets{2.3.6} [Not Enough Pets] (NotEnoughPets-1.7.10-2.3.6.jar) 
	UC	nova_craft{1.3.1} [NovaCraft] (NovaCraft+V1.3.1+(1.7.10).jar) 
	UC	optimizationsandtweaks{0.8.7.4.2} [Optimizations and Tweaks] (optimizationsandtweaks-V1.13.1.jar) 
	UC	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's+HarvestCraft+1.7.10Lb.jar) 
	UC	plug{5.1} [The Plugin Mod] (PluginMod-5.1.jar) 
	UC	sampler{1.60.1} [Sampling Performance Profiler] (sampler-1.60.1.jar) 
	UC	squidless{0.6.1} [Squidless] (squidless-1.7.10-0.6.1.jar) 
	UC	teresetfix{1.0.1-noreq} [TileEntity Reset Fix] (TileEntityResetFix-1.0.1-noreq.jar) 
	UC	ZoocraftDiscoveries{1.0} [Zoocraft Discoveries]
```
This same issue happens with lwjgl3ify 2.0.0-alpha-2-snapshot and 1.5.14 on java 8

**Comment by bombcar** [comment]
Could you try running the lwjgl3ify version of GTNH from your prism/multimc launcher under Linux?

**Comment by reuben-matus** [comment]
So just the GTHN modpack with lwjgl3ify added to it?

**Comment by eigenraven** [comment]
This looks like you installed lwjgl3ify wrong, the lwjgl 3 jars are missing from the classpath. Are you sure you extracted the forgePatches jar over your instance and see LWJGL3 in the library list of your instance?

**Comment by reuben-matus** [comment]
Nevermind I did indeed install it wrong, needed to read the non-GTHN section, whoops sorry guys

**Comment by eigenraven** [comment]
Post the full crash log please

**Comment by reuben-matus** [comment]
Sure here's the link to the log prism launcher gives me:
https://mclo.gs/UpxXYHY

**Comment by reuben-matus** [comment]
With the alpha-3 2.0 it now runs but crashes with custom npc plus and Flan's Mod NPC Vehicles

**Comment by eigenraven** [comment]
Please test again with alpha 9

**Comment by reuben-matus** [comment]
Still unfortunately crashes with error:
Description: There was a severe problem during mod loading that has caused the game to fail
cpw.mods.fml.common.LoaderException: java.lang.IllegalAccessError: class jdk.nashorn.internal.codegen.types.Type (in unnamed module @0x35229f85) cannot access class jdk.internal.org.objectweb.asm.Type (in module java.base) because module java.base does not export jdk.internal.org.objectweb.asm to unnamed module @0x35229f85
	at RFB-Launch//cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at RFB-Launch//cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at RFB-Launch//cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at RFB-Launch//net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at RFB-Launch//net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:9993)
	at RFB-Launch//net.minecraft.client.main.Main.main(SourceFile:148)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at RFB-System//net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:248)
	at RFB-System//net.minecraft.launchwrapper.Launch.launch(Launch.java:35)
	at RFB-System//net.minecraft.launchwrapper.Launch.main(Launch.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:219)
	at RFB-System//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at RFB-System//org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at RFB-System//org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.IllegalAccessError: class jdk.nashorn.internal.codegen.types.Type (in unnamed module @0x35229f85) cannot access class jdk.internal.org.objectweb.asm.Type (in module java.base) because module java.base does not export jdk.internal.org.objectweb.asm to unnamed module @0x35229f85
	at RFB-Launch//jdk.nashorn.internal.codegen.types.Type.getInternalName(Type.java:415)
	at RFB-Launch//jdk.nashorn.internal.codegen.CompilerConstants.className(CompilerConstants.java:299)
	at RFB-Launch//jdk.nashorn.internal.codegen.CompilerConstants.staticCallNoLookup(CompilerConstants.java:438)
	at RFB-Launch//jdk.nashorn.internal.codegen.types.Type.<clinit>(Type.java:128)
	at RFB-Launch//jdk.nashorn.internal.codegen.CompilerConstants.className(CompilerConstants.java:299)
	at RFB-Launch//jdk.nashorn.internal.codegen.CompilerConstants.virtualCall(CompilerConstants.java:604)
	at RFB-Launch//jdk.nashorn.internal.runtime.GlobalConstants.<clinit>(GlobalConstants.java:98)
	at RFB-Launch//jdk.nashorn.internal.runtime.Context.createOrInvalidateGlobalConstants(Context.java:1124)
	at RFB-Launch//jdk.nashorn.internal.runtime.Context.newGlobal(Context.java:1110)
	at RFB-Launch//jdk.nashorn.api.scripting.NashornScriptEngine$2.run(NashornScriptEngine.java:350)
	at RFB-Launch//jdk.nashorn.api.scripting.NashornScriptEngine$2.run(NashornScriptEngine.java:346)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at RFB-Launch//jdk.nashorn.api.scripting.NashornScriptEngine.createNashornGlobal(NashornScriptEngine.java:346)
	at RFB-Launch//jdk.nashorn.api.scripting.NashornScriptEngine.<init>(NashornScriptEngine.java:143)
	at RFB-Launch//jdk.nashorn.api.scripting.NashornScriptEngineFactory.getScriptEngine(NashornScriptEngineFactory.java:148)
	at RFB-Launch//noppes.npcs.controllers.ScriptController.<init>(ScriptController.java:63)
	at RFB-Launch//noppes.npcs.CustomNpcs.load(CustomNpcs.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at RFB-Launch//cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at RFB-System//com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at RFB-System//com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at RFB-System//com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at RFB-System//com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at RFB-System//com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at RFB-Launch//cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at RFB-Launch//cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at RFB-System//com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at RFB-System//com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at RFB-System//com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at RFB-System//com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at RFB-System//com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at RFB-Launch//cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at RFB-Launch//cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 19 more

**Comment by reuben-matus** [comment]
Error is fixed 👍
