### ISSUE TITLE
PerfectSpawn Transformer Error with Angelica

### ISSUE THREAD

**Issue by JL2210** [GTNewHorizons/lwjgl3ify#154]
https://www.curseforge.com/minecraft/mc-mods/perfect-spawn

https://github.com/lumien231/Perfect-Spawn/blob/aa9f96ec93c24d3157493270ccc322aef9008d46/src/main/java/lumien/perfectspawn/Transformer/PSClassTransformer.java#L43

\*only happens with Angelica installed?

Relevant log excerpt:

```
[04:23:24] [Server thread/DEBUG] [PerfectSpawnCore/]: Transforming org.spongepowered.asm.synthetic.args.Args$1
[04:23:24] [Server thread/DEBUG] [LaunchWrapper/]: Transformer error
java.lang.ClassNotFoundException: Exception caught while transforming class org.spongepowered.asm.synthetic.args.Args$1
	at RFB-System//net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:293) [LaunchClassLoader.class:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592) [?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) [?:?]
	at RFB-Launch//net.minecraft.server.management.ServerConfigurationManager.func_72372_a(ServerConfigurationManager.java:246) [oi.class:?]
	at RFB-Launch//net.minecraft.entity.EntityTracker.<init>(EntityTracker.java:56) [mn.class:?]
	at RFB-Launch//net.minecraft.world.WorldServer.<init>(WorldServer.java:99) [mt.class:?]
	at RFB-Launch//net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62) [bsx.class:?]
	at RFB-Launch//net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) [bsx.class:?]
	at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.NullPointerException: Cannot read the array length because "classFile" is null
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166) ~[lwjgl3ify-2.0.9-forgePatches.jar:?]
	at RFB-Launch//lumien.perfectspawn.Transformer.PSClassTransformer.transform(PSClassTransformer.java:43) ~[PSClassTransformer.class:?]
	at RFB-System//net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:404) ~[LaunchClassLoader.class:?]
	at RFB-System//net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:291) ~[LaunchClassLoader.class:?]
	... 9 more
```

Full log:
[fml-client-latest.zip](https://github.com/GTNewHorizons/lwjgl3ify/files/15496175/fml-client-latest.zip)

Not super sure whether to report this here (maybe Hodgepodge?). Followed non-GTNH 1.7.10 instance setup on Blightfall 3.1.1-CE, installed Angelica, and replaced ForgeMultipart with 1.5.0. Loading in a new world causes this error. Prism Launcher 8.3 if that's relevant

**Comment by JL2210** [comment]
Sorry. Not an lwjgl3ify issue.
