### ISSUE TITLE
OmniOcular use in a java9+ environment will cause a crash

### ISSUE THREAD

**Issue by mcmso** [GTNewHorizons/lwjgl3ify#21]
I don't know where I should feedback this issue, but you deserve my trust

[latest.log](https://github.com/GTNewHorizons/lwjgl3ify/files/10803382/latest.log)
[crash-2023-02-22_19.42.03-client.txt](https://github.com/GTNewHorizons/lwjgl3ify/files/10803386/crash-2023-02-22_19.42.03-client.txt)
Please contact me if you need any additional information

**Comment by eigenraven** [comment]
Relevant error (for my reference):
```

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: javax/servlet/Servlet
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5093)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.NoClassDefFoundError: javax/servlet/Servlet
    at me.exz.omniocular.proxy.ClientProxy.startHttpServer(ClientProxy.java:60)
    at me.exz.omniocular.OmniOcular.preInit(OmniOcular.java:27)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    ... 11 more
Caused by: java.lang.ClassNotFoundException: javax.servlet.Servlet
    at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
    at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:119)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:588)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    ... 34 more
```

**Comment by mcmso** [comment]
[
[fml-client-latest.log](https://github.com/GTNewHorizons/lwjgl3ify/files/10803531/fml-client-latest.log)
fml-junk-earlystartup.log](https://github.com/GTNewHorizons/lwjgl3ify/files/10803523/fml-junk-earlystartup.log)
[GregTech.log](https://github.com/GTNewHorizons/lwjgl3ify/files/10803527/GregTech.log)
[latest.log](https://github.com/GTNewHorizons/lwjgl3ify/files/10803528/latest.log)
[LootGames.log](https://github.com/GTNewHorizons/lwjgl3ify/files/10803529/LootGames.log)
[Explosion.log](https://github.com/GTNewHorizons/lwjgl3ify/files/10803530/Explosion.log)

**Comment by mcmso** [comment]
To replicate this bug, just add OmniOcular-1.7.10-1.0build107.jar to gtnh java9+
Then on startup the progress bar gets stuck at 33%
A crash-report is generated at the same time

**Comment by eigenraven** [comment]
Where did you get the build107 jar? The latest version on curse is 103 (it doesn't refer to Servlet at all), and the latest on github uses a different servlet api. I attempted a fix in 1.1.34, but I can't test it myself because I can't find your version on the internet

**Comment by mcmso** [comment]
> Where did you get the build107 jar? The latest version on curse is 103 (it doesn't refer to Servlet at all), and the latest on github uses a different servlet api. I attempted a fix in 1.1.34, but I can't test it myself because I can't find your version on the internet

In fact, after reading your message, I immediately researched the source of this version 107, but I did not find the source.

**Comment by mcmso** [comment]
[OmniOcular-1.7.10-1.0build107.zip](https://github.com/GTNewHorizons/lwjgl3ify/files/10870979/OmniOcular-1.7.10-1.0build107.zip)

**Comment by mcmso** [comment]
You can test it by changing the suffix to jar

**Comment by LasmGratel** [comment]
It still crashes (using both latest version)
```
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "me.exz.omniocular.handler.JSHandler.engine" is null
	at me.exz.omniocular.handler.JSHandler.getBody(JSHandler.java:44)
	at me.exz.omniocular.handler.TooltipHandler.handleItemTooltip(TooltipHandler.java:32)
	at codechicken.nei.guihook.GuiContainerManager.renderToolTips(GuiContainerManager.java:411)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:166)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:1536)
	at com.bioxx.tfc.GUI.GuiInventoryTFC.func_73863_a(GuiInventoryTFC.java:189)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at me.exz.omniocular.handler.JSHandler.getBody(JSHandler.java:44)
	at me.exz.omniocular.handler.TooltipHandler.handleItemTooltip(TooltipHandler.java:32)
	at codechicken.nei.guihook.GuiContainerManager.renderToolTips(GuiContainerManager.java:411)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:166)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:1536)
	at com.bioxx.tfc.GUI.GuiInventoryTFC.func_73863_a(GuiInventoryTFC.java:189)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
```

**Comment by LasmGratel** [comment]
I solved this by using an alternative version of OmniOcular: <https://www.curseforge.com/minecraft/mc-mods/omni-ocular/files/4475975>
