### ISSUE TITLE
Crash with just another spawner

### ISSUE THREAD

**Issue by unix-supremacist** [GTNewHorizons/lwjgl3ify#38]
lwjgl3ify version:1.1.37

[crash-2023-03-12_09.46.50-server.txt](https://github.com/GTNewHorizons/lwjgl3ify/files/10951324/crash-2023-03-12_09.46.50-server.txt)
[latest.log](https://github.com/GTNewHorizons/lwjgl3ify/files/10951325/latest.log)

crash happens on world load

**Comment by Radplay** [comment]
Happens with lwjgl3ify 1.5.0 as well

Crash report: https://mclo.gs/EPMDLlW
Latest.log: https://mclo.gs/ZVuOgcW

**Comment by Radk6** [comment]
Re-tested it with lwjgl3ify 2.0.0-alpha-7. The game doesn't crash now, but it's now impossible to enter a world with JAS installed. Log: https://mclo.gs/K3g71vt

**Comment by eigenraven** [comment]
notes for me: java.lang.Compiler remapper is not catching the class being used as a LDC constant

**Comment by eigenraven** [comment]
New crash:
```
java.lang.VerifyError: (class: ASMAccessorImpl_1501138191719743711470, method: getValue signature: (Ljava/lang/Object;Ljava/lang/Object;Lorg/mvel2/integration/VariableResolverFactory;)Ljava/lang/Object;) Illegal type in constant pool
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:?]
	at java.base/java.lang.Class.getConstructor0(Unknown Source) ~[?:?]
	at java.base/java.lang.Class.getConstructor(Unknown Source) ~[?:?]
	at Launch//org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer._initializeAccessor(ASMAccessorOptimizer.java:730) ~[ASMAccessorOptimizer.class:?]
	at Launch//org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.compileAccessor(ASMAccessorOptimizer.java:857) ~[ASMAccessorOptimizer.class:?]
	at Launch//org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeAccessor(ASMAccessorOptimizer.java:245) ~[ASMAccessorOptimizer.class:?]
	at Launch//org.mvel2.optimizers.dynamic.DynamicGetAccessor.optimize(DynamicGetAccessor.java:96) ~[DynamicGetAccessor.class:?]
	at Launch//org.mvel2.optimizers.dynamic.DynamicGetAccessor.getValue(DynamicGetAccessor.java:66) ~[DynamicGetAccessor.class:?]
	at Launch//org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:108) ~[ASTNode.class:?]
	at Launch//org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:38) ~[ExecutableAccessor.class:?]
	at Launch//org.mvel2.ast.Negation.getReducedValueAccelerated(Negation.java:48) ~[Negation.class:?]
	at Launch//org.mvel2.ast.Or.getReducedValueAccelerated(Or.java:34) ~[Or.class:?]
	at Launch//org.mvel2.ast.Or.getReducedValueAccelerated(Or.java:34) ~[Or.class:?]
	at Launch//org.mvel2.ast.Or.getReducedValueAccelerated(Or.java:34) ~[Or.class:?]
	at Launch//org.mvel2.ast.Or.getReducedValueAccelerated(Or.java:34) ~[Or.class:?]
	at Launch//org.mvel2.ast.Or.getReducedValueAccelerated(Or.java:34) ~[Or.class:?]
	at Launch//org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:42) ~[ExecutableAccessor.class:?]
	at Launch//org.mvel2.MVEL.executeExpression(MVEL.java:954) ~[MVEL.class:?]
	at Launch//jas.common.helper.MVELHelper.typedExecuteExpression(MVELHelper.java:16) ~[MVELHelper.class:?]
	at Launch//jas.common.helper.MVELHelper.executeExpression(MVELHelper.java:10) ~[MVELHelper.class:?]
	at Launch//jas.spawner.modern.spawner.creature.type.CreatureType.canSpawnAtLocation(CreatureType.java:162) ~[CreatureType.class:?]
	at Launch//jas.spawner.modern.spawner.creature.type.CreatureType.canSpawnHere(CreatureType.java:251) ~[CreatureType.class:?]
	at Launch//jas.spawner.modern.spawner.CustomSpawner.spawnCreaturesInChunks(CustomSpawner.java:72) ~[CustomSpawner.class:?]
	at Launch//jas.spawner.modern.spawner.SpawnerTicker.performSpawningInWorld(SpawnerTicker.java:73) ~[SpawnerTicker.class:?]
	at Launch//jas.spawner.modern.spawner.SpawnerTicker.serverTick(SpawnerTicker.java:42) ~[SpawnerTicker.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_19_SpawnerTicker_serverTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at Launch//cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260) ~[FMLCommonHandler.class:?]
	at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536) ~[MinecraftServer.class:?]
	at Launch//net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
	```

OSS at https://github.com/ProjectZulu/JustAnotherSpawner
