### ISSUE TITLE
Incompatibility with OptiFine D6

### ISSUE THREAD

**Issue by makamys** [GTNewHorizons/lwjgl3ify#47]
I'm not sure if there's any way to fix this from LWJGL3ify's side, but I figured it would be worth reporting.

OptiFine D6 obtains a ZipFile reference to its own jar file roughly like this:
```java
URLClassLoader ucl = (URLClassLoader)OptiFineClassTransformer.class.getClassLoader();
URL[] urls = ucl.getURLs();
// ...
ZipFile self = new ZipFile(new File(urls[i]));
```
An exception happens on the first line since in new versions of Java, `AppClassLoader` is no longer a subclass of `URLClassLoader`.

```
[15:00:19] [main/INFO] [LaunchWrapper/]: Calling tweak class optifine.OptiFineForgeTweaker
[15:00:19] [main/INFO] [STDOUT/]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[15:00:19] [main/INFO] [STDOUT/]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[15:00:19] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
[15:00:19] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at optifine.OptiFineClassTransformer.<init>(OptiFineClassTransformer.java:40)
[15:00:19] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
[15:00:19] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[15:00:19] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
[15:00:19] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:94)
[15:00:19] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at optifine.OptiFineForgeTweaker.injectIntoClassLoader(OptiFineForgeTweaker.java:38)
[15:00:19] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:145)
[15:00:19] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
[15:00:19] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
[15:00:19] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
[15:00:19] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
[15:00:19] [main/INFO] [STDOUT/]: [optifine.OptiFineClassTransformer:dbg:266]: *** Can not find the OptiFine JAR in the classpath ***
[15:00:19] [main/INFO] [STDOUT/]: [optifine.OptiFineClassTransformer:dbg:266]: *** OptiFine will not be loaded! ***
```

OptiFine E7 doesn't have this problem, since it instead uses `OptiFineClassTransformer.class.getProtectionDomain().getCodeSource().getLocation()` to get the URL. The reason D6 is relevant is because it [has been found](https://github.com/FalsePattern/FalseTweaks/issues/15#issuecomment-1150770307) to give better performance than E7 in some cases.

**Comment by LasmGratel** [comment]
Is there any shaders mod compatible with lwjgl3ify?

**Comment by makamys** [comment]
I have released a tiny mod that hacks Java 9 compat into OptiFine D6, so a workaround exists now.
https://github.com/makamys/OptiFine3ify

**Comment by Dream-Master** [comment]
oh cool so we can use Fastcraft 1.2.3 and Optifine D6 ontop with newest java version :)

**Comment by makamys** [comment]
With FastCraft 1.23 + OptiFine D6, disabling `stbiTextureStiching` is required because the flashing issue happens otherwise. I'll make a PR that updates the auto-detection logic in a moment.

**Comment by eigenraven** [comment]
Fixed in alpha 6.
