### ISSUE TITLE
Error loading FoamFix (MacOS – Prism Launcher – Java 20 – lwgjlify v1.3.4)

### ISSUE THREAD

**Issue by kadirac** [GTNewHorizons/lwjgl3ify#54]
When attempting to run lwgjl3ify with FoamFix, I received the following crash:
```log
[13:23:12] [Client thread/INFO] [lwjgl3ify]: Lwjgl3ify preInit - Java version 18
[13:23:12] [Client thread/INFO] [FML]: Applying holder lookups
[13:23:12] [Client thread/INFO] [FML]: Holder lookups applied
[13:23:12] [Client thread/INFO] [FML]: Injecting itemstacks
[13:23:12] [Client thread/INFO] [FML]: Itemstack injection complete
[13:23:12] [Client thread/ERROR] [FML]: Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
[13:23:12] [Client thread/ERROR] [FML]: 
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCH	FoamFixCore{1.0.3} [FoamFixCore] (minecraft.jar) 
	UCH	unimixins{0.1.6} [UniMixins] (_unimixins-all-1.7.10-0.1.6.jar) 
	UCH	unimixins-mixin{0.1.6} [UniMixins: Mixin (UniMix)] (_unimixins-all-1.7.10-0.1.6.jar) 
	UCH	unimixins-compat{0.1.6} [UniMixins: Compatibility] (_unimixins-all-1.7.10-0.1.6.jar) 
	UCH	mixingasm{0.2.2} [UniMixins: Mixingasm] (_unimixins-all-1.7.10-0.1.6.jar) 
	UCH	gtnhmixins{2.1.9} [UniMixins: GTNHMixins] (_unimixins-all-1.7.10-0.1.6.jar) 
	UCH	spongemixins{2.0.1} [UniMixins: SpongeMixins] (_unimixins-all-1.7.10-0.1.6.jar) 
	UCH	mixinbooterlegacy{1.2.1} [UniMixins: MixinBooterLegacy] (_unimixins-all-1.7.10-0.1.6.jar) 
	UCH	gasstation{0.5.1} [UniMixins: GasStation] (_unimixins-all-1.7.10-0.1.6.jar) 
	UCH	mixinextras{0.1.6} [UniMixins: MixinExtras] (_unimixins-all-1.7.10-0.1.6.jar) 
	UCE	foamfix{@VERSION@} [FoamFix] (FoamFix-1.7.10-universal-1.0.3.jar) 
	UCH	lwjgl3ify{1.3.4} [lwjgl3ify] (lwjgl3ify-1.3.4.jar) 
[13:23:12] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[13:23:12] [Client thread/ERROR] [FML]: Caught exception from foamfix
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at pl.asie.foamfix.FoamFixMod.preinit(FoamFixMod.java:61) ~[FoamFix-1.7.10-universal-1.0.3.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165) [launchwrapper-1.15.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29) [launchwrapper-1.15.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
```
The full log can be found at [https://pastebin.com/pVSNtXbq](https://pastebin.com/pVSNtXbq). I can move it here if that's preferable.
Loading without FoamFix + with some other mods (ArchaicFix, Optifine, GTNHLib, Hodgepodge) ran without issues.
An issue from a few weeks ago (#32) seems to imply FoamFix worked fine in the past; I'm not sure if this is a regression, specific to MacOS, or something I set up wrong ~~(most likely :,)~~

**Comment by eigenraven** [comment]
A fix has already been merged to foamfix (<https://github.com/asiekierka/FoamFix17/commit/1f932e9d09c70455f5ba6a6ab2583ee84518b85e>), you might have to wait for @asiekierka to release a new version or build it yourself.

**Comment by asiekierka** [comment]
FoamFix 1.0.4 includes the fix
