### ISSUE TITLE
java.lang.NoClassDefFoundError: java/util/jar/Pack200

### ISSUE THREAD

**Issue by wxb2468235** [GTNewHorizons/lwjgl3ify#55]
jdk17
[12:22:39] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:22:39] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[12:22:39] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:22:39] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:22:39] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:22:39] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:22:39] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: java.lang.NoClassDefFoundError: java/util/jar/Pack200
[12:22:39] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at cpw.mods.fml.common.patcher.ClassPatchManager.setup(ClassPatchManager.java:161)
[12:22:39] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at cpw.mods.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:181)
[12:22:39] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:132)
[12:22:39] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:145)
[12:22:39] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
[12:22:39] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: Caused by: java.lang.ClassNotFoundException: java.util.jar.Pack200
[12:22:39] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[12:22:39] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[12:22:39] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[12:22:39] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:119)
[12:22:39] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[12:22:39] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

**Comment by Glease** [comment]
Either forgePatches.jar didn't apply, or you were using very ancient lwjgl3ify.

**Comment by wxb2468235** [comment]
is used：lwjgl3ify-1.3.4.jar

**Comment by wxb2468235** [comment]
lwjgl3ify-1.3.4-forgePatches.jar

**Comment by wxb2468235** [comment]
java.lang.IllegalArgumentException: java.lang.ClassCastException@1ca25c47
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleCascadingTweak(CoreModManager.java:405) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:342) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:145) [launchwrapper-1.15.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29) [launchwrapper-1.15.jar:?]
[13:16:44] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:16:44] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[13:16:44] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:16:44] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:16:44] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:16:44] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:16:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: java.lang.NoClassDefFoundError: java/util/jar/Pack200
[13:16:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at cpw.mods.fml.common.patcher.ClassPatchManager.setup(ClassPatchManager.java:161)
[13:16:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at cpw.mods.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:181)
[13:16:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:132)
[13:16:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:145)
[13:16:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
[13:16:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: Caused by: java.lang.ClassNotFoundException: java.util.jar.Pack200
[13:16:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[13:16:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[13:16:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[13:16:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:119)
[13:16:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[13:16:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

**Comment by Glease** [comment]
Really, this is just another symptom of forgePatches not being properly applied. Either the file is corrupted (in which case you should download one manually from github release) or you didn't use the patch json file to apply it.

**Comment by eigenraven** [comment]
This seems to be a broken installation, follow the instructions in the readme and if you need any more help you need to post full launcher logs and not just the exception part.
