### ISSUE TITLE
lwjgl3ify breaking Raw Input

### ISSUE THREAD

**Issue by Taskeren** [GTNewHorizons/lwjgl3ify#61]
[Raw Input](https://github.com/seanld03/RawInputMod-1.12.2-1.7.10) depends on JInput, which seemed to be removed in J17 version.

Is there any work around to make it working?

exception log:
<details>
<pre>
Caused by: java.lang.ClassNotFoundException: net.java.games.input.ControllerEnvironment
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:212) ~[launchwrapper-1.15.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 46 more
</pre>
</details>

**Comment by eigenraven** [comment]
I fixed the missing inpufix jars, and raw input seems to be working fine for me on linux except for mouse movement but it doesn't work for me on standard 1.7.10+forge either so it should be fine for you

**Comment by Taskeren** [comment]
Raw Input is only for the mouse movement improvement.
If it is not working, maybe something has changed in mouse movement logic, because JInput is no longer a hard dependency.

I’ll try it when I’m home.
