### ISSUE TITLE
LiteLoader incompatibility

### ISSUE THREAD

**Issue by Firara** [GTNewHorizons/lwjgl3ify#67]
Log here: 
https://mclo.gs/vS64Du1

**Comment by eigenraven** [comment]
Caused by LiteLoader incomaptibility, I'll have to look into whether/how this would be fixable:
```
[12:47:45] [main/ERROR] [LiteLoader]: ClassPathUtilities: Error initialising ClassPathUtilities, special class path injection disabled
java.lang.NoClassDefFoundError: sun/misc/URLClassPath
        at com.mumfrey.liteloader.launch.ClassPathUtilities.<clinit>(ClassPathUtilities.java:71) [liteloader-1.7.10-client.jar:1.7.10_04]
	at com.mumfrey.liteloader.interfaces.LoadableFile.injectIntoClassPath(LoadableFile.java:251) [LoadableFile.class:1.7.10_04]
	at com.mumfrey.liteloader.core.LiteLoaderEnumerator.addClassTransformersFrom(LiteLoaderEnumerator.java:598) [LiteLoaderEnumerator.class:1.7.10_04]
	at com.mumfrey.liteloader.core.LiteLoaderEnumerator.addTweaksFrom(LiteLoaderEnumerator.java:542) [LiteLoaderEnumerator.class:1.7.10_04]
	at com.mumfrey.liteloader.core.LiteLoaderEnumerator.injectDiscoveredTweaks(LiteLoaderEnumerator.java:395) [LiteLoaderEnumerator.class:1.7.10_04]
	at com.mumfrey.liteloader.core.LiteLoaderEnumerator.onPreInit(LiteLoaderEnumerator.java:366) [LiteLoaderEnumerator.class:1.7.10_04]
	at com.mumfrey.liteloader.core.LiteLoaderBootstrap.preInit(LiteLoaderBootstrap.java:297) [LiteLoaderBootstrap.class:1.7.10_04]
	at com.mumfrey.liteloader.launch.LiteLoaderTweaker.onPreInit(LiteLoaderTweaker.java:314) [liteloader-1.7.10-client.jar:1.7.10_04]
	at com.mumfrey.liteloader.launch.LiteLoaderTweaker.acceptOptions(LiteLoaderTweaker.java:220) [liteloader-1.7.10-client.jar:1.7.10_04]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:144) [launchwrapper-1.15.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29) [launchwrapper-1.15.jar:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: sun.misc.URLClassPath
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 20 more
```

**Comment by eigenraven** [comment]
LiteLoader should now work fine with lwjgl3ify 2.0.0 alpha 10 - I tested it with VoxelMap and it seems to work fine.
Make sure to check the README instructions regarding installing liteloader in multimc/prism:
https://github.com/GTNewHorizons/lwjgl3ify/blob/0914eca019f07d40111610f40db980a21fe5e21f/README.MD#liteloader-compatibility
