### ISSUE TITLE
Crash with UniMixins 0.1.12

### ISSUE THREAD

**Issue by RoBaertschi** [GTNewHorizons/lwjgl3ify#89]
# How to replicate
Install lwjgl3ify and UniMixins 0.1.12. It should fail to launch.

# Workaround
UniMixins 0.1.11 works, so there is probably an incompatibility introduced in UniMixins 0.1.12.

# Crashlog
[Full Crashlog](https://mclo.gs/l32FaRe)

The Crashlog starts with one Mixin Error, then some line later is full of other errors: Module requires ASM6. I suspect that these are a product of the first error about the mixin.

I suspect the following Error to be the root of the problem because it doesen't happen with earlier versions of UniMixins:
```
java.lang.reflect.InvocationTargetException
--
153 | at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119) ~[?:?]
154 | at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
155 | at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.injectCorePlugin(MixinPlatformAgentFMLLegacy.java:255) ~[ unimixins-all-1.7.10-0.1.12.jar:0.12.2 mixin.0.8.5]
156 | at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.initFMLCoreMod(MixinPlatformAgentFMLLegacy.java:170) ~[ unimixins-all-1.7.10-0.1.12.jar:0.12.2 mixin.0.8.5]
157 | at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.accept(MixinPlatformAgentFMLLegacy.java:156) ~[ unimixins-all-1.7.10-0.1.12.jar:0.12.2 mixin.0.8.5]
158 | at org.spongepowered.asm.launch.platform.MixinContainer.<init>(MixinContainer.java:74) ~[ unimixins-all-1.7.10-0.1.12.jar:0.12.2 mixin.0.8.5]
159 | at org.spongepowered.asm.launch.platform.MixinPlatformManager.createContainerFor(MixinPlatformManager.java:149) ~[ unimixins-all-1.7.10-0.1.12.jar:0.12.2 mixin.0.8.5]
160 | at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:136) ~[ unimixins-all-1.7.10-0.1.12.jar:0.12.2 mixin.0.8.5]
161 | at org.spongepowered.asm.launch.platform.MixinPlatformManager.init(MixinPlatformManager.java:105) ~[ unimixins-all-1.7.10-0.1.12.jar:0.12.2 mixin.0.8.5]
162 | at org.spongepowered.asm.launch.MixinBootstrap.getPlatform(MixinBootstrap.java:118) ~[ unimixins-all-1.7.10-0.1.12.jar:0.12.2 mixin.0.8.5]
163 | at org.spongepowered.asm.launch.MixinBootstrap.start(MixinBootstrap.java:166) ~[ unimixins-all-1.7.10-0.1.12.jar:0.12.2 mixin.0.8.5]
164 | at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:46) ~[ unimixins-all-1.7.10-0.1.12.jar:0.12.2 mixin.0.8.5]
165 | at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) [?:?]
166 | at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) [?:?]
167 | at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484) [?:?]
168 | at net.minecraft.launchwrapper.Launch.launch(Launch.java:125) [lwjgl3ify-1.5.2-forgePatches.jar:?]
169 | at net.minecraft.launchwrapper.Launch.main(Launch.java:29) [lwjgl3ify-1.5.2-forgePatches.jar:?]
170 | at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
171 | at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
172 | at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]

// This is probably the error

>> 173 | Caused by: java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class com/gtnewhorizon/mixinextras/utils/MixinExtrasLogger. Method 'java.lang.Object lambda$get$0(java.lang.Object, java.lang.Object, java.lang.reflect.Method, java.lang.Object[])' at index 92 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
174 | at com.gtnewhorizon.mixinextras.utils.MixinExtrasLogger.get(MixinExtrasLogger.java:37) ~[ unimixins-all-1.7.10-0.1.12.jar:0.12.2 mixin.0.8.5]
175 | at com.gtnewhorizon.mixinextras.service.MixinExtrasServiceImpl.<clinit>(MixinExtrasServiceImpl.java:24) ~[ unimixins-all-1.7.10-0.1.12.jar:0.12.2 mixin.0.8.5]
176 | at com.gtnewhorizon.mixinextras.service.MixinExtrasService.setup(MixinExtrasService.java:28) ~[ unimixins-all-1.7.10-0.1.12.jar:0.12.2 mixin.0.8.5]
177 | at com.gtnewhorizon.mixinextras.MixinExtrasBootstrap.init(MixinExtrasBootstrap.java:20) ~[ unimixins-all-1.7.10-0.1.12.jar:0.12.2 mixin.0.8.5]
178 | at com.gtnewhorizon.gtnhmixins.core.GTNHMixinsCore.<clinit>(GTNHMixinsCore.java:49) ~[ unimixins-all-1.7.10-0.1.12.jar:0.12.2 mixin.0.8.5]
179 | at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
180 | at java.base/java.lang.Class.forName(Class.java:391) ~[?:?]
181 | at java.base/java.lang.Class.forName(Class.java:382) ~[?:?]
182 | at io.github.legacymoddingmc.unimixins.all.AllCore.<clinit>(AllCore.java:22) ~[ unimixins-all-1.7.10-0.1.12.jar:0.12.2 mixin.0.8.5]
183 | at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
184 | at java.base/java.lang.Class.forName(Class.java:496) ~[?:?]
185 | at java.base/java.lang.Class.forName(Class.java:475) ~[?:?]
186 | at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:492) ~[lwjgl3ify-1.5.2-forgePatches.jar:?]
187 | at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
188 | ... 19 more

```

**Comment by RoBaertschi** [comment]
I looked into UniMixins changes since 0.1.11 and there were some changes with MixinExtras and the error looks like that these changes maybe are responsible for the problem.

**Comment by mitchej123** [comment]
Unimixins 0.1.13 should work, wait until that's released.

**Comment by RoBaertschi** [comment]
0.1.13 fixed the issue
